name: Check flake
on: push
jobs:
  check:
    name: Check flake
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v15
        with:
          extra_nix_config: access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - run: nix flake check

  update:
    needs: check
    if: github.event.ref == 'refs/heads/master'
    uses: ./.github/workflows/update.yml
